# -*- coding: utf-8 -*-
"""CapStone Modul 2 Ai Engineering Purwadhika - Muda

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3WSGhlCYTol2mXiSrXsppV6KmRQJC58

1. Masalah Bisnis dan Pemahaman Data

### 1.1 Context

Apartemen menjadi solusi hunian populer di kota-kota besar seperti Daegu, Korea Selatan. Pemilik unit apartemen — baik individu maupun perusahaan — dapat menawarkan unitnya melalui platform properti dengan menentukan harga sendiri. Namun, tanpa referensi harga yang akurat, pemilik sering kali salah dalam menetapkan harga:
- **Harga terlalu tinggi** → unit sulit terjual
- **Harga terlalu rendah** → pemilik kehilangan potensi profit

### 1.2 Stakeholder
Pemilik unit apartemen di Daegu yang ingin menjual unitnya dan membutuhkan estimasi harga pasar yang objektif.

### 1.3 Problem Statement
Bagaimana cara memprediksi harga jual apartemen (`SalePrice`) secara akurat berdasarkan karakteristik unit dan lingkungan sekitarnya, sehingga pemilik unit dapat menetapkan harga yang kompetitif?

### 1.4 Goals
Membangun model **regresi** machine learning yang dapat memprediksi `SalePrice` dengan error sekecil mungkin.

### 1.5 Analytic Approach
Karena target variabel (`SalePrice`) bersifat **kontinu**, maka pendekatan yang digunakan adalah **supervised learning — regression**.

### 1.6 Evaluation Metrics
| Metric | Alasan |
|--------|--------|
| **MAPE** | Mengukur error dalam persentase, mudah diinterpretasikan oleh non-technical stakeholder |
| **RMSE** | Sensitif terhadap outlier, cocok untuk data harga yang bervariasi |
| **R²** | Mengukur seberapa baik model menjelaskan variasi harga |

> **Focus metric: MAPE** — karena stakeholder lebih mudah memahami "model meleset X%" dibanding nilai absolut dalam Won.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import OneHotEncoder, RobustScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error, r2_score

from sklearn.linear_model import LinearRegression, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor

import pickle

pd.set_option('display.max_columns', None)

df = pd.read_csv('data_daegu_apartment.csv')
print(f'Shape: {df.shape}')
df.head()

"""### 2.1 Data Understanding

| Kolom | Tipe | Deskripsi |
|-------|------|-----------|
| HallwayType | Kategorikal | Tipe koridor apartemen (terraced, mixed, corridor) |
| TimeToSubway | Kategorikal | Waktu tempuh ke stasiun subway terdekat |
| SubwayStation | Kategorikal | Nama stasiun subway terdekat |
| N_FacilitiesNearBy(ETC) | Numerik | Jumlah fasilitas umum di sekitar |
| N_FacilitiesNearBy(PublicOffice) | Numerik | Jumlah kantor publik di sekitar |
| N_SchoolNearBy(University) | Numerik | Jumlah universitas di sekitar |
| N_Parkinglot(Basement) | Numerik | Jumlah slot parkir basement |
| YearBuilt | Numerik | Tahun pembangunan apartemen |
| N_FacilitiesInApt | Numerik | Jumlah fasilitas dalam apartemen |
| Size(sqf) | Numerik | Luas apartemen (sqft) |
| **SalePrice** | **Target** | **Harga jual apartemen (Won)** |
"""

df.info()

df.describe()

"""---
## 3. Data Cleaning, Feature Selection & Feature Engineering

### 3.1 Cek Missing Values
"""

print('Missing values:')
print(df.isnull().sum())

"""> Dataset tidak memiliki missing values, sehingga tidak diperlukan imputasi.

### 3.2 Cek Duplikat
"""

print(f'Jumlah duplikat: {df.duplicated().sum()}')
df = df.drop_duplicates()
print(f'Shape setelah hapus duplikat: {df.shape}')

"""### 3.3 Cek & Tangani Outlier

Outlier ditangani menggunakan metode **IQR (Interquartile Range)**. Data di luar batas bawah dan atas IQR dihapus karena bisa memperburuk performa model regresi.
"""

num_cols = ['N_FacilitiesNearBy(ETC)', 'N_FacilitiesNearBy(PublicOffice)',
            'N_SchoolNearBy(University)', 'N_Parkinglot(Basement)',
            'N_FacilitiesInApt', 'Size(sqf)', 'SalePrice']

df_clean = df.copy()
for col in num_cols:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df_clean = df_clean[(df_clean[col] >= lower) & (df_clean[col] <= upper)]

print(f'Shape sebelum: {df.shape}')
print(f'Shape setelah hapus outlier: {df_clean.shape}')

"""### 3.4 Feature Engineering

Membuat fitur baru `ApartmentAge` dari `YearBuilt` untuk merepresentasikan umur apartemen yang lebih informatif dibanding tahun pembangunan mentah.
"""

df_clean['ApartmentAge'] = 2024 - df_clean['YearBuilt']
df_clean = df_clean.drop(columns=['YearBuilt'])
df_clean.head()

"""---
## 4. Analytics — Modeling & Evaluation

### 4.1 Train-Test Split
"""

X = df_clean.drop(columns=['SalePrice'])
y = df_clean['SalePrice']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f'Train: {X_train.shape}, Test: {X_test.shape}')

"""### 4.2 Preprocessing Pipeline

- **Kolom numerik** → `RobustScaler` (tahan terhadap outlier sisa)
- **Kolom kategorikal** → `OneHotEncoder`
"""

cat_cols = ['HallwayType', 'TimeToSubway', 'SubwayStation']
num_cols_model = ['N_FacilitiesNearBy(ETC)', 'N_FacilitiesNearBy(PublicOffice)',
                  'N_SchoolNearBy(University)', 'N_Parkinglot(Basement)',
                  'N_FacilitiesInApt', 'Size(sqf)', 'ApartmentAge']

preprocessor = ColumnTransformer([
    ('num', RobustScaler(), num_cols_model),
    ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
])

"""### 4.3 Benchmark Model

Membandingkan beberapa algoritma untuk memilih model terbaik sebagai base:
"""

def evaluate_model(name, model, X_train, X_test, y_train, y_test):
    pipe = Pipeline([('preprocessor', preprocessor), ('model', model)])
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    mape = mean_absolute_percentage_error(y_test, y_pred) * 100
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)
    print(f'{name:30s} | MAPE: {mape:.2f}% | RMSE: {rmse:,.0f} | R²: {r2:.4f}')
    return pipe

models = {
    'Linear Regression': LinearRegression(),
    'Decision Tree': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(random_state=42),
    'Gradient Boosting': GradientBoostingRegressor(random_state=42),
    'XGBoost': XGBRegressor(random_state=42, verbosity=0)
}

print(f'{"Model":30s} | {"MAPE":10s} | {"RMSE":12s} | R²')
print('-' * 65)
for name, model in models.items():
    evaluate_model(name, model, X_train, X_test, y_train, y_test)

"""### 4.4 Hyperparameter Tuning (Final Model)

Berdasarkan benchmark, **[model terbaik]** dipilih untuk dituning lebih lanjut menggunakan `GridSearchCV`.

> **Catatan:** Ganti `XGBRegressor` di bawah jika model lain yang terbaik dari benchmark.
"""

param_grid = {
    'model__n_estimators': [100, 200],
    'model__max_depth': [3, 5, 7],
    'model__learning_rate': [0.05, 0.1]
}

final_pipe = Pipeline([('preprocessor', preprocessor), ('model', XGBRegressor(random_state=42, verbosity=0))])

grid_search = GridSearchCV(final_pipe, param_grid, cv=5,
                           scoring='neg_mean_absolute_percentage_error',
                           n_jobs=-1, verbose=1)
grid_search.fit(X_train, y_train)

print(f'Best Params: {grid_search.best_params_}')
print(f'Best CV MAPE: {-grid_search.best_score_*100:.2f}%')

best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

mape = mean_absolute_percentage_error(y_test, y_pred) * 100
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print('=== Final Model Performance ===')
print(f'MAPE : {mape:.2f}%')
print(f'RMSE : {rmse:,.0f} Won')
print(f'R²   : {r2:.4f}')

"""### 4.5 Feature Importance"""

# Ambil nama fitur setelah preprocessing
ohe_features = best_model.named_steps['preprocessor'].named_transformers_['cat'].get_feature_names_out(cat_cols)
all_features = num_cols_model + list(ohe_features)

importances = best_model.named_steps['model'].feature_importances_
feat_imp = pd.Series(importances, index=all_features).sort_values(ascending=False).head(10)

plt.figure(figsize=(8, 5))
feat_imp.plot(kind='barh', color='steelblue')
plt.title('Top 10 Feature Importances')
plt.xlabel('Importance Score')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

"""---
## 5. Conclusion & Recommendation

### 5.1 Kesimpulan

- Model **[nama model]** dipilih sebagai final model dengan performa terbaik di antara semua model yang diuji.
- Model mencapai **MAPE ≈ X%**, artinya rata-rata prediksi harga apartemen meleset sekitar X% dari harga aktual.
- Fitur yang paling berpengaruh terhadap harga adalah **Size(sqf)**, **ApartmentAge**, dan **N_Parkinglot(Basement)**.
- Model ini dapat membantu pemilik unit apartemen di Daegu mendapatkan referensi harga yang lebih objektif sebelum listing.

### 5.2 Kapan Model Dapat Dipercaya?

✅ **Model dapat dipercaya** ketika:
- Ukuran apartemen berada dalam rentang data training (tidak ekstrem)
- Lokasi apartemen ada di salah satu stasiun subway yang tercakup dalam data
- Tahun pembangunan masuk dalam rentang data

⚠️ **Model kurang dapat dipercaya** ketika:
- Apartemen memiliki ukuran atau harga yang sangat jauh dari rata-rata (ekstrem outlier)
- Lokasi atau stasiun subway tidak terdata sebelumnya
- Kondisi pasar properti berubah signifikan (inflasi, kebijakan baru, dll)

### 5.3 Rekomendasi & Improvement

1. **Tambah fitur lokasi** seperti koordinat GPS atau jarak ke pusat kota untuk meningkatkan akurasi.
2. **Update data secara berkala** karena harga properti sangat dipengaruhi kondisi pasar yang berubah.
3. **Pertimbangkan fitur ekonomi makro** seperti suku bunga dan tingkat inflasi sebagai fitur tambahan.
4. **Gunakan model yang lebih canggih** seperti LightGBM atau CatBoost untuk potensi performa yang lebih baik.

---
## 6. Save Model
"""

with open('daegu_apartment_model.pkl', 'wb') as f:
    pickle.dump(best_model, f)

print('Model berhasil disimpan sebagai daegu_apartment_model.pkl')

!pip install scikit-learn==1.6.1 -q

import pickle
with open('daegu_apartment_model.pkl', 'rb') as f:
    model = pickle.load(f)

print(type(model))

import pandas as pd

data_baru = pd.DataFrame({
    'N_FacilitiesNearBy(ETC)': [10],
    'N_FacilitiesNearBy(PublicOffice)': [5],
    'N_SchoolNearBy(University)': [2],
    'N_Parkinglot(Basement)': [1],
    'N_FacilitiesInApt': [8],
    'Size(sqf)': [800],
    'ApartmentAge': [10],
    'HallwayType': ['corridor'],       # contoh: 'corridor', 'mixed', 'terraced'
    'TimeToSubway': ['0-5min'],        # contoh: '0-5min', '5min~10min', dll
    'SubwayStation': ['Banwoldang']    # nama stasiun subway di Daegu
})

prediksi = model.predict(data_baru)
print(f"Prediksi harga: {prediksi[0]:,.0f}")

print(df['HallwayType'].unique())
print(df['TimeToSubway'].unique())
print(df['SubwayStation'].unique())

